In [2]:
from google.colab import files

# This will open a file chooser dialog
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))


Saving car.data to car.data
User uploaded file "car.data" with length 51209 bytes


In [4]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from matplotlib import pyplot as plt

data = pd.read_csv('car.data')
print(data.head())

X = data[['buying', 'maint', 'safety']].values
X = np.array(X)
print(X)
#converting data
#X
Le = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = Le.fit_transform(X[:, i])
print(X)
#y
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y = data['class'].map(label_mapping).values # Fix for SettingWithCopyWarning and DataConversionWarning

#create model
print(X.shape)
print(y.shape) # Now y.shape will be (1728,)

knn = svm.SVC()
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, prediction)
print("predictions:", prediction)
print("accuracy: ", accuracy)
a = 1727
print("actual value ", y[a])
print("predicted value", knn.predict(X)[a])

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]
[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
(1728, 3)
(1728,)
predictions: [0 0 1 0 0 1 0 0 1 1 0 2 0 2 1 0 1 1 1 1 2 1 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1
 0 1 0 1 2 0 1 2 0 1 1 0 2 0 2 0 2 1 2 0 0 1 0 2 2 1 1 1 1 1 1 0 0 0 1 1 1
 0 2 2 0 1 2 1 0 2 1 0 3 0 1 1 1 0 1 0 0 0 1 1 0 2 1 0 1 1 0 0 0 0 0 1 0 0
 0 2 1 2 1 0 1 0 0 1 1 0 1 2 0 1 0 0 1 2 0 2 1 1 1 0 1 1 1 2 0 0 0 1 0 1 1
 0 1 1 1 1 1 1 1 0 1 2 1 1 0 1 2 2 1 0 1 1 0 0 0 0 1 1 0 1 0 2 0 0 0 0 0 0
 2 1 0 1 0 0 0 1 0 0 0 1 0 1 2 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 1 2 2 1